#change null to 'NULL'

chuck = Senator.create({
                 "id": "S000148",
                 "title": "Senator, 3rd Class",
                 "short_title": "Sen.",
                 "api_uri":"https://api.propublica.org/congress/v1/members/S000148.json",
                 "first_name": "Charles",
                 "middle_name": "E.",
                 "last_name": "Schumer",
                 "suffix": "NULL",
                 "date_of_birth": "1950-11-23",
                 "gender": "M",
                 "party": "D",
                 "leadership_role": "Senate Minority Leader",
                 "twitter_account": "SenSchumer",
                 "facebook_account": "senschumer",
                 "youtube_account": "SenatorSchumer",
                 "govtrack_id": "300087",
                 "cspan_id": "5929",
                 "votesmart_id": "26976",
                 "icpsr_id": "14858",
                 "crp_id": "N00001093",
                 "google_entity_id": "/m/01w74d",
                 "fec_candidate_id": "S8NY00082",
                 "url": "https://www.schumer.senate.gov",
                 "rss_url": "NULL",
                 "contact_form": "https://www.schumer.senate.gov/contact/email-chuck",
                 "in_office": true,
                 "cook_pvi": "NULL",
                 "dw_nominate": -0.354,
                 "ideal_point": "NULL",
                 "seniority": "21",
                 "next_election": "2022",
                 "total_votes": 352,
                 "missed_votes": 0,
                 "total_present": 1,
                 "last_updated": "2019-11-08 06:54:49 -0500",
                 "ocd_id": "ocd-division/country:us/state:ny",
                 "office": "322 Hart Senate Office Building",
                 "phone": "202-224-6542",
                 "fax": "202-228-3027",
                 "state": "NY",
                 "senate_class": "3",
                 "state_rank": "senior",
                 "lis_id": "S270",
                 "missed_votes_pct": 0.00,
                 "votes_with_party_pct": 90.96,
                 "votes_against_party_pct": 9.04
               })

tom = Senator.create({
                 "id": "U000039",
                 "title": "Senator, 2nd Class",
                 "short_title": "Sen.",
                 "api_uri":"https://api.propublica.org/congress/v1/members/U000039.json",
                 "first_name": "Tom",
                 "middle_name": "NULL",
                 "last_name": "Udall",
                 "suffix": "NULL",
                 "date_of_birth": "1948-05-18",
                 "gender": "M",
                 "party": "D",
                 "leadership_role": "",
                 "twitter_account": "SenatorTomUdall",
                 "facebook_account": "senatortomudall",
                 "youtube_account": "senatortomudall",
                 "govtrack_id": "400413",
                 "cspan_id": "10075",
                 "votesmart_id": "22658",
                 "icpsr_id": "29924",
                 "crp_id": "N00006561",
                 "google_entity_id": "/m/033t35",
                 "fec_candidate_id": "H8NM03097",
                 "url": "https://www.tomudall.senate.gov",
                 "rss_url": "NULL",
                 "contact_form": "https://www.tomudall.senate.gov/?p=contact",
                 "in_office": true,
                 "cook_pvi": "NULL",
                 "dw_nominate": -0.452,
                 "ideal_point": "NULL",
                 "seniority": "12",
                 "next_election": "2020",
                 "total_votes": 352,
                 "missed_votes": 4,
                 "total_present": 1,
                 "last_updated": "2019-11-08 06:54:50 -0500",
                 "ocd_id": "ocd-division/country:us/state:nm",
                 "office": "531 Hart Senate Office Building",
                 "phone": "202-224-6621",
                 "fax": "202-228-3261",
                 "state": "NM",
                 "senate_class": "2",
                 "state_rank": "senior",
                 "lis_id": "S326",
                 "missed_votes_pct": 1.14,
                 "votes_with_party_pct": 94.10,
                 "votes_against_party_pct": 5.90
               })