require 'pry'
# NOTES 
#
# Raw API JSON data can be found in ./raw/[branch].json
#
# Importer will fail if any values are null or nil
# 
# Update these values to 'NULL' (as string)
api_data = {
    "status":"OK",
    "copyright":"Copyright (c) 2019 Pro Publica Inc. All Rights Reserved.",
    "results":[
       {
          
          
          "num_results": 20,
          "offset": 0,
          "bills": [
               {
                  "bill_id": "sres396-116",
                  "bill_slug": "sres396",
                  "bill_type": "sres",
                  "number": "S.RES.396",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/sres396.json",
                  "title": "A resolution designating October 2019 as \"National Health Literacy Month\".",
                  "short_title": "A resolution designating October 2019 as \"National Health Literacy Month\".",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "M001169",
                  "sponsor_name": "Christopher S. Murphy",
                  "sponsor_state": "CT",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001169.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-resolution/396",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/sres396",
                  "introduced_date": "2019-10-31",
                  "active": true,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 3,
                  "cosponsors_by_party": {"R":2,"D":1},
                  "committees": "Senate Judiciary Committee",
                  "committee_codes": ["SSJU"],
                  "subcommittee_codes": [],
                  "primary_subject": "",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-11-06",
                  "latest_major_action": "Resolution agreed to in Senate without amendment and with a preamble by Unanimous Consent. (text: 2019/10/31 CR S6340)"
               },
                            {
                  "bill_id": "hr3055-116",
                  "bill_slug": "hr3055",
                  "bill_type": "hr",
                  "number": "H.R.3055",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr3055.json",
                  "title": "Making appropriations for the Departments of Commerce and Justice, Science, and Related Agencies for the fiscal year ending September 30, 2020, and for other purposes.",
                  "short_title": "Commerce, Justice, Science, Agriculture, Rural Development, Food and Drug Administration, Interior, Environment, Transportation, and Housing and Urban Development Appropriations Act, 2020",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "S000248",
                  "sponsor_name": "José E. Serrano",
                  "sponsor_state": "NY",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/S000248.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/3055",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr3055",
                  "introduced_date": "2019-06-03",
                  "active": true,
                  "last_vote": "2019-10-31",
                  "house_passage": "2019-06-25",
                  "senate_passage": "2019-10-31",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "House Appropriations Committee",
                  "committee_codes": ["HSAP"],
                  "subcommittee_codes": [],
                  "primary_subject": "Economics and Public Finance",
                  "summary": "Commerce, Justice, Science, Agriculture, Rural Development, Food and Drug Administration, Interior, Environment, Transportation, and Housing and Urban Development Appropriations Act, 2020 This bill provides FY2020 appropriations for several federal departments and agencies. It includes 4 of the 12 regular FY2020 appropriations bills:   the Commerce, Justice, Science, and Related Agencies Appropriations Act, 2020; the Agriculture, Rural Development, Food and Drug Administration, and Related Agencies Appropriations Act, 2020; the Department of the Interior, Environment, and Related Agencies Appropriations Act, 2020; and the Transportation, Housing and Urban Development, and Related Agencies Appropriations Act, 2020.   The departments and agencies funded in the bill include    the Department of Commerce;   the Department of Justice;   science-related agencies, including the National Aeronautics and Space Administration (NASA); the Department of Agriculture; the Food and Drug Administration; the Department of the Interior;  the Environmental Protection Agency;  the Forest Service;   the Department of Transportation;   the Department of Housing and Urban Development; and   several additional related and independent agencies.   The bill also specifies restrictions and requirements for using funds provided by this and other appropriations Acts.",
                  "summary_short": "Commerce, Justice, Science, Agriculture, Rural Development, Food and Drug Administration, Interior, Environment, Transportation, and Housing and Urban Development Appropriations Act, 2020 This bill provides FY2020 appropriations for several federal departments and agencies. It includes 4 of the 12 regular FY2020 appropriations bills:   the Commerce, Justice, Science, and Related Agencies Appropriations Act, 2020; the Agriculture, Rural Development, Food and Drug Administration, and Related Ag...",
                  "latest_major_action_date": "2019-11-04",
                  "latest_major_action": "Message on Senate action sent to the House."
               },
                            {
                  "bill_id": "s2760-116",
                  "bill_slug": "s2760",
                  "bill_type": "s",
                  "number": "S.2760",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/s2760.json",
                  "title": "A bill to amend the Richard B. Russell National School Lunch Act to enhance direct certification under the school lunch program.",
                  "short_title": "Caregivers, Access, and Responsible Expansion for Kids Act of 2019",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "C001070",
                  "sponsor_name": "Bob Casey",
                  "sponsor_state": "PA",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001070.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-bill/2760",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/s2760",
                  "introduced_date": "2019-10-31",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "Senate Agriculture, Nutrition, and Forestry Committee",
                  "committee_codes": ["SSAF"],
                  "subcommittee_codes": [],
                  "primary_subject": "",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-31",
                  "latest_major_action": "Read twice and referred to the Committee on Agriculture, Nutrition, and Forestry."
               },
                            {
                  "bill_id": "sres401-116",
                  "bill_slug": "sres401",
                  "bill_type": "sres",
                  "number": "S.RES.401",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/sres401.json",
                  "title": "A resolution recognizing the month of October 2019 as Filipino American History Month and celebrating the history and culture of Filipino Americans and their immense contributions to the United States.",
                  "short_title": "A resolution recognizing the month of October 2019 as Filipino American History Month and celebrating the history and culture of Filipino Americans and their immense contributions to the United States.",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "H001042",
                  "sponsor_name": "Mazie K. Hirono",
                  "sponsor_state": "HI",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/H001042.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-resolution/401",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/sres401",
                  "introduced_date": "2019-10-31",
                  "active": true,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 18,
                  "cosponsors_by_party": {"R":1,"D":16,"ID":1},
                  "committees": "",
                  "committee_codes": [],
                  "subcommittee_codes": [],
                  "primary_subject": "Immigration",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-31",
                  "latest_major_action": "Submitted in the Senate, considered, and agreed to without amendment and with a preamble by Unanimous Consent. (consideration: CR S6357; text: CR S6342-6343)"
               },
                            {
                  "bill_id": "hr2740-116",
                  "bill_slug": "hr2740",
                  "bill_type": "hr",
                  "number": "H.R.2740",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr2740.json",
                  "title": "Making appropriations for the Departments of Labor, Health and Human Services, and Education, and related agencies for the fiscal year ending September 30, 2020, and for other purposes.",
                  "short_title": "Labor, Health and Human Services, Education, Defense, State, Foreign Operations, and Energy and Water Development Appropriations Act, 2020",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "D000216",
                  "sponsor_name": "Rosa DeLauro",
                  "sponsor_state": "CT",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/D000216.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/2740",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr2740",
                  "introduced_date": "2019-05-15",
                  "active": true,
                  "last_vote": "2019-10-31",
                  "house_passage": "2019-06-19",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "House Appropriations Committee",
                  "committee_codes": ["HSAP"],
                  "subcommittee_codes": [],
                  "primary_subject": "Economics and Public Finance",
                  "summary": "Labor, Health and Human Services, Education, Defense, State, Foreign Operations, and Energy and Water Development Appropriations Act, 2020 This bill provides FY2020 appropriations for several federal departments and agencies. It includes 4 of the 12 regular FY2020 appropriations bills:    the Departments of Labor, Health and Human Services, and Education, and Related Agencies Appropriations Act, 2020; the Department of Defense Appropriations Act, 2020; the Department of State, Foreign Operations, and Related Programs Appropriations Act, 2020; and the Energy and Water Development and Related Agencies Appropriations Act, 2020.  The departments and agencies funded in the bill include   the Department of Labor, the Department of Health and Human Services, the Department of Education,  the Department of Defense, the Department of State, the Department of Energy, the U.S. Army Corps of Engineers,  the Bureau of Reclamation, and  several related and independent agencies.   The bill also specifies restrictions and requirements for using funds provided by this and other appropriations Acts. ",
                  "summary_short": "Labor, Health and Human Services, Education, Defense, State, Foreign Operations, and Energy and Water Development Appropriations Act, 2020 This bill provides FY2020 appropriations for several federal departments and agencies. It includes 4 of the 12 regular FY2020 appropriations bills:    the Departments of Labor, Health and Human Services, and Education, and Related Agencies Appropriations Act, 2020; the Department of Defense Appropriations Act, 2020; the Department of State, Foreign Operati...",
                  "latest_major_action_date": "2019-10-31",
                  "latest_major_action": "Motion by Senator McConnell to reconsider the vote by which the third cloture on the motion to proceed to H.R. 2740 was not invoked (Record Vote No. 342) entered in Senate."
               },
                            {
                  "bill_id": "hres666-116",
                  "bill_slug": "hres666",
                  "bill_type": "hres",
                  "number": "H.RES.666",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hres666.json",
                  "title": "Expressing the sense of the House of Representatives on the ratification of the United Nations Covenant on Economic, Social and Cultural Rights.",
                  "short_title": "Expressing the sense of the House of Representatives on the ratification of the United Nations Covenant on Economic, Social and Cultural Rights.",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "O000172",
                  "sponsor_name": "Alexandria Ocasio-Cortez",
                  "sponsor_state": "NY",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/O000172.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-resolution/666",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hres666",
                  "introduced_date": "2019-10-30",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 5,
                  "cosponsors_by_party": {"D":5},
                  "committees": "House Foreign Affairs Committee",
                  "committee_codes": ["HSFA"],
                  "subcommittee_codes": [],
                  "primary_subject": "International Affairs",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-30",
                  "latest_major_action": "Referred to the House Committee on Foreign Affairs."
               },
                            {
                  "bill_id": "hr4935-116",
                  "bill_slug": "hr4935",
                  "bill_type": "hr",
                  "number": "H.R.4935",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr4935.json",
                  "title": "To prohibit chemical abortions performed without the presence of a healthcare provider, and for other purposes.",
                  "short_title": "To prohibit chemical abortions performed without the presence of a healthcare provider, and for other purposes.",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "W000827",
                  "sponsor_name": "Ron Wright",
                  "sponsor_state": "TX",
                  "sponsor_party": "R",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/W000827.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/4935",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr4935",
                  "introduced_date": "2019-10-30",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 16,
                  "cosponsors_by_party": {"R":16},
                  "committees": "House Judiciary Committee",
                  "committee_codes": ["HSJU"],
                  "subcommittee_codes": [],
                  "primary_subject": "",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-30",
                  "latest_major_action": "Referred to the House Committee on the Judiciary."
               },
                            {
                  "bill_id": "hr4897-116",
                  "bill_slug": "hr4897",
                  "bill_type": "hr",
                  "number": "H.R.4897",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr4897.json",
                  "title": "To amend the Internal Revenue Code of 1986 to increase the amount excluded from gross income by reason of distributions from governmental retirement plans for health and long-term care insurance for public safety officers.",
                  "short_title": "Public Safety Retirees Healthcare Protection Act",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "L000563",
                  "sponsor_name": "Daniel Lipinski",
                  "sponsor_state": "IL",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000563.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/4897",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr4897",
                  "introduced_date": "2019-10-29",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "House Ways and Means Committee",
                  "committee_codes": ["HSWM"],
                  "subcommittee_codes": [],
                  "primary_subject": "Taxation",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-29",
                  "latest_major_action": "Referred to the House Committee on Ways and Means."
               },
                            {
                  "bill_id": "hr2781-116",
                  "bill_slug": "hr2781",
                  "bill_type": "hr",
                  "number": "H.R.2781",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr2781.json",
                  "title": "To amend title VII of the Public Health Service Act to reauthorize certain programs relating to the health professions workforce, and for other purposes.",
                  "short_title": "Educating Medical Professionals and Optimizing Workforce Efficiency and Readiness for Health Act of 2019",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "S001145",
                  "sponsor_name": "Jan Schakowsky",
                  "sponsor_state": "IL",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/S001145.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/2781",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr2781",
                  "introduced_date": "2019-05-16",
                  "active": true,
                  "last_vote": "NULL",
                  "house_passage": "2019-10-28",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 15,
                  "cosponsors_by_party": {"R":4,"D":11},
                  "committees": "Senate Health, Education, Labor, and Pensions Committee",
                  "committee_codes": ["SSHR","HSIF"],
                  "subcommittee_codes": ["HSIF14"],
                  "primary_subject": "Health",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-29",
                  "latest_major_action": "Received in the Senate and Read twice and referred to the Committee on Health, Education, Labor, and Pensions."
               },
                            {
                  "bill_id": "hr4460-116",
                  "bill_slug": "hr4460",
                  "bill_type": "hr",
                  "number": "H.R.4460",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr4460.json",
                  "title": "To provide funding for programs and activities under the SUPPORT for Patients and Communities Act.",
                  "short_title": "Turn the Tide Act",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "K000382",
                  "sponsor_name": "Ann McLane Kuster",
                  "sponsor_state": "NH",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/K000382.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/4460",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr4460",
                  "introduced_date": "2019-09-24",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 1,
                  "cosponsors_by_party": {"D":1},
                  "committees": "House Judiciary Committee",
                  "committee_codes": ["HSIF"],
                  "subcommittee_codes": ["HSJU08"],
                  "primary_subject": "Health",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-28",
                  "latest_major_action": "Referred to the Subcommittee on Crime, Terrorism, and Homeland Security."
               },
                            {
                  "bill_id": "s2721-116",
                  "bill_slug": "s2721",
                  "bill_type": "s",
                  "number": "S.2721",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/s2721.json",
                  "title": "A bill to reduce violence and health disparities by addressing social determinants of health, enhancing health care recruitment, and improving the delivery of quality, coordinated care services, and for other purposes.",
                  "short_title": "Healing Communities through Health Care Act",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "D000563",
                  "sponsor_name": "Richard J. Durbin",
                  "sponsor_state": "IL",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/D000563.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-bill/2721",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/s2721",
                  "introduced_date": "2019-10-28",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "Senate Health, Education, Labor, and Pensions Committee",
                  "committee_codes": ["SSHR"],
                  "subcommittee_codes": [],
                  "primary_subject": "",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-28",
                  "latest_major_action": "Read twice and referred to the Committee on Health, Education, Labor, and Pensions. (text: CR S6191-6193)"
               },
                            {
                  "bill_id": "sres379-116",
                  "bill_slug": "sres379",
                  "bill_type": "sres",
                  "number": "S.RES.379",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/sres379.json",
                  "title": "A resolution supporting the designation of September 2019 as \"National Alcohol and Drug Addiction Recovery Month\".",
                  "short_title": "A resolution supporting the designation of September 2019 as \"National Alcohol and Drug Addiction Recovery Month\".",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "K000383",
                  "sponsor_name": "Angus King",
                  "sponsor_state": "ME",
                  "sponsor_party": "I",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/K000383.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-resolution/379",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/sres379",
                  "introduced_date": "2019-10-24",
                  "active": true,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 2,
                  "cosponsors_by_party": {"R":1,"D":1},
                  "committees": "",
                  "committee_codes": [],
                  "subcommittee_codes": [],
                  "primary_subject": "",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-24",
                  "latest_major_action": "Submitted in the Senate, considered, and agreed to without amendment and with a preamble by Voice Vote. (consideration: CR S6177; text: CR S6161)"
               },
                            {
                  "bill_id": "hr4769-116",
                  "bill_slug": "hr4769",
                  "bill_type": "hr",
                  "number": "H.R.4769",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr4769.json",
                  "title": "To amend part D of title XVIII of the Social Security Act to deliver a meaningful benefit and lower prescription drug prices under the Medicare program.",
                  "short_title": "Medicare Prescription Drug Savings and Choice Act of 2019",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "S001145",
                  "sponsor_name": "Jan Schakowsky",
                  "sponsor_state": "IL",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/S001145.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/4769",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr4769",
                  "introduced_date": "2019-10-21",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "House Ways and Means Committee",
                  "committee_codes": ["HSIF"],
                  "subcommittee_codes": [],
                  "primary_subject": "Health",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-21",
                  "latest_major_action": "Referred to the Committee on Energy and Commerce, and in addition to the Committee on Ways and Means, for a period to be subsequently determined by the Speaker, in each case for consideration of such provisions as fall within the jurisdiction of the committee concerned."
               },
                            {
                  "bill_id": "s2650-116",
                  "bill_slug": "s2650",
                  "bill_type": "s",
                  "number": "S.2650",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/s2650.json",
                  "title": "A bill to amend part D of title XVIII of the Social Security Act to deliver a meaningful benefit and lower prescription drug prices under the Medicare program.",
                  "short_title": "Medicare Prescription Drug Savings and Choice Act of 2019",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "D000563",
                  "sponsor_name": "Richard J. Durbin",
                  "sponsor_state": "IL",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/D000563.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-bill/2650",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/s2650",
                  "introduced_date": "2019-10-21",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 1,
                  "cosponsors_by_party": {"D":1},
                  "committees": "Senate Finance Committee",
                  "committee_codes": ["SSFI"],
                  "subcommittee_codes": [],
                  "primary_subject": "Health",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-21",
                  "latest_major_action": "Read twice and referred to the Committee on Finance. (text: CR S5924-5925)"
               },
                            {
                  "bill_id": "s2613-116",
                  "bill_slug": "s2613",
                  "bill_type": "s",
                  "number": "S.2613",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/s2613.json",
                  "title": "A bill to provide a path to end homelessness in the United States, and for other purposes.",
                  "short_title": "Ending Homelessness Act of 2019",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "H001075",
                  "sponsor_name": "Kamala Harris",
                  "sponsor_state": "CA",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/H001075.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-bill/2613",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/s2613",
                  "introduced_date": "2019-10-16",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 6,
                  "cosponsors_by_party": {"D":6},
                  "committees": "Senate Banking, Housing, and Urban Affairs Committee",
                  "committee_codes": ["SSBK"],
                  "subcommittee_codes": [],
                  "primary_subject": "Housing and Community Development",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-16",
                  "latest_major_action": "Read twice and referred to the Committee on Banking, Housing, and Urban Affairs."
               },
                            {
                  "bill_id": "hr4651-116",
                  "bill_slug": "hr4651",
                  "bill_type": "hr",
                  "number": "H.R.4651",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr4651.json",
                  "title": "To amend the Internal Revenue Code of 1986 to expand health savings accounts, and for other purposes.",
                  "short_title": "American Future Healthcare Act of 2019",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "K000362",
                  "sponsor_name": "Steve King",
                  "sponsor_state": "IA",
                  "sponsor_party": "R",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/K000362.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/4651",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr4651",
                  "introduced_date": "2019-10-11",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "House Ways and Means Committee",
                  "committee_codes": ["HSWM"],
                  "subcommittee_codes": [],
                  "primary_subject": "Taxation",
                  "summary": "American Future Healthcare Act of 2019  This bill amends the Internal Revenue Code, with respect to health savings accounts (HSAs), to   repeal the requirement that an individual making a tax deductible contribution to an HSA be covered by a high deductible health care plan;  increase the maximum HSA contribution level;  allow Medicare eligible individuals to contribute to an HSA;  allow HSAs to be used to purchase health insurance;  provide a cost-of-living adjustment for the limits on additional contributions for individuals 55 or older (catch-up contributions);  require the cost-of-living adjustments to be indexed to the CPI medical care component (the medical care component for the Consumer Price Index for All Urban Consumers published by the Department of Labor);  allow a rollover of HSA amounts to a Medicare Advantage Medical Savings Account (MSA); and  treat direct primary care service arrangement fees as deductible medical expenses.  This bill also allows an individual with alternative health coverage to opt out of Medicare hospital services benefits without also having to opt out of Old Age, Survivors, and Disability Insurance benefits and without having to repay Medicare hospital services benefits already received. ",
                  "summary_short": "American Future Healthcare Act of 2019  This bill amends the Internal Revenue Code, with respect to health savings accounts (HSAs), to   repeal the requirement that an individual making a tax deductible contribution to an HSA be covered by a high deductible health care plan;  increase the maximum HSA contribution level;  allow Medicare eligible individuals to contribute to an HSA;  allow HSAs to be used to purchase health insurance;  provide a cost-of-living adjustment for the limits on addit...",
                  "latest_major_action_date": "2019-10-11",
                  "latest_major_action": "Referred to the House Committee on Ways and Means."
               },
                            {
                  "bill_id": "hr4322-116",
                  "bill_slug": "hr4322",
                  "bill_type": "hr",
                  "number": "H.R.4322",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr4322.json",
                  "title": "To promote cannabis research, and for other purposes.",
                  "short_title": "Expanding Cannabis Research and Information Act",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "S001206",
                  "sponsor_name": "Donna Shalala",
                  "sponsor_state": "FL",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/S001206.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/4322",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr4322",
                  "introduced_date": "2019-09-12",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 3,
                  "cosponsors_by_party": {"R":1,"D":2},
                  "committees": "House Judiciary Committee",
                  "committee_codes": ["HSIF"],
                  "subcommittee_codes": ["HSJU08"],
                  "primary_subject": "Health",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-02",
                  "latest_major_action": "Referred to the Subcommittee on Crime, Terrorism, and Homeland Security."
               },
                            {
                  "bill_id": "hr4584-116",
                  "bill_slug": "hr4584",
                  "bill_type": "hr",
                  "number": "H.R.4584",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/hr4584.json",
                  "title": "To amend the Higher Education Act of 1965 to repeal the suspension of eligibility for assistance under title IV due to drug-related offenses.",
                  "short_title": "Financial Aid Fairness for Students Act",
                  "sponsor_title": "Rep.",
                  "sponsor_id": "B001270",
                  "sponsor_name": "Karen Bass",
                  "sponsor_state": "CA",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/B001270.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/house-bill/4584",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/hr4584",
                  "introduced_date": "2019-10-01",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 37,
                  "cosponsors_by_party": {"D":36,"R":1},
                  "committees": "House Education and Labor",
                  "committee_codes": ["HSED"],
                  "subcommittee_codes": [],
                  "primary_subject": "Education",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-10-01",
                  "latest_major_action": "Referred to the House Committee on Education and Labor."
               },
                            {
                  "bill_id": "s2577-116",
                  "bill_slug": "s2577",
                  "bill_type": "s",
                  "number": "S.2577",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/s2577.json",
                  "title": "A bill to require data brokers to establish procedures to ensure the accuracy of collected personal information, and for other purposes.",
                  "short_title": "Data Broker Accountability and Transparency Act of 2019",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "M000133",
                  "sponsor_name": "Edward J. Markey",
                  "sponsor_state": "MA",
                  "sponsor_party": "D",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/M000133.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-bill/2577",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/s2577",
                  "introduced_date": "2019-09-26",
                  "active": false,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 2,
                  "cosponsors_by_party": {"D":2},
                  "committees": "Senate Commerce, Science, and Transportation Committee",
                  "committee_codes": ["SSCM"],
                  "subcommittee_codes": [],
                  "primary_subject": "",
                  "summary": "",
                  "summary_short": "",
                  "latest_major_action_date": "2019-09-26",
                  "latest_major_action": "Read twice and referred to the Committee on Commerce, Science, and Transportation."
               },
                            {
                  "bill_id": "s2580-116",
                  "bill_slug": "s2580",
                  "bill_type": "s",
                  "number": "S.2580",
                  "bill_uri": "https://api.propublica.org/congress/v1/116/bills/s2580.json",
                  "title": "An original bill making appropriations for the Department of the Interior, environment, and related agencies for the fiscal year ending September 30, 2020, and for other purposes.",
                  "short_title": "Department of the Interior, Environment, and Related Agencies Appropriations Act, 2020",
                  "sponsor_title": "Sen.",
                  "sponsor_id": "M001153",
                  "sponsor_name": "Lisa Murkowski",
                  "sponsor_state": "AK",
                  "sponsor_party": "R",
                  "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001153.json",
                  "gpo_pdf_uri": "NULL",
                  "congressdotgov_url": "https://www.congress.gov/bill/116th-congress/senate-bill/2580",
                  "govtrack_url": "https://www.govtrack.us/congress/bills/116/s2580",
                  "introduced_date": "2019-09-26",
                  "active": true,
                  "last_vote": "NULL",
                  "house_passage": "NULL",
                  "senate_passage": "NULL",
                  "enacted": "NULL",
                  "vetoed": "NULL",
                  "cosponsors": 0,
                  "cosponsors_by_party": {},
                  "committees": "Senate Appropriations Committee",
                  "committee_codes": ["SSAP"],
                  "subcommittee_codes": [],
                  "primary_subject": "Economics and Public Finance",
                  "summary": "Department of the Interior, Environment, and Related Agencies Appropriations Act, 2020 This bill provides FY2020 appropriations for the Department of the Interior, the Environmental Protection Agency (EPA), and related agencies.  The bill provides appropriations to Interior for   the Bureau of Land Management,  the U.S. Fish and Wildlife Service,   the National Park Service,  the U.S. Geological Survey,  the Bureau of Ocean Energy Management,  the Bureau of Safety and Environmental Enforcement,  the Office of Surface Mining Reclamation and Enforcement,   the Bureau of Indian Affairs, the Bureau of Indian Education, Departmental Offices, and  Department-Wide Programs.  The bill provides appropriations to the EPA and the Forest Service.  Within the Department of Health and Human Services, the bill provides appropriations for   the Indian Health Service,   the National Institute of Environmental Health Sciences, and   the Agency for Toxic Substances and Disease Registry.   The bill provides appropriations to several related agencies, including   the Executive Office of the President for the Council on Environmental Quality and the Office of Environmental Quality;  the Chemical Safety and Hazard Investigation Board;   the Office of Navajo and Hopi Indian Relocation;   the Institute of American Indian and Alaska Native Culture and Arts Development;   the Smithsonian Institution;   the National Gallery of Art;   the John F. Kennedy Center for the Performing Arts;   the Woodrow Wilson International Center for Scholars;   the National Foundation on the Arts and Humanities, including the National Endowment for the Arts and the National Endowment for the Humanities;   the Commission of Fine Arts;   the Advisory Council on Historic Preservation;   the National Capital Planning Commission;   the U.S. Holocaust Memorial Museum; the Dwight D. Eisenhower Memorial Commission;  the Women's Suffrage Centennial Commission; the World War I Centennial Commission; and the Alyce Spotted Bear and Walter Soboleff Commission on Native Children.  Additionally, the bill sets forth requirements and restrictions for using funds provided by this and other appropriations Acts. ",
                  "summary_short": "Department of the Interior, Environment, and Related Agencies Appropriations Act, 2020 This bill provides FY2020 appropriations for the Department of the Interior, the Environmental Protection Agency (EPA), and related agencies.  The bill provides appropriations to Interior for   the Bureau of Land Management,  the U.S. Fish and Wildlife Service,   the National Park Service,  the U.S. Geological Survey,  the Bureau of Ocean Energy Management,  the Bureau of Safety and Environmental Enforcemen...",
                  "latest_major_action_date": "2019-09-26",
                  "latest_major_action": "Placed on Senate Legislative Calendar under General Orders. Calendar No. 227."
               }
              ]
       }
    ]
 }

 BILLS = api_data[:results][0][:bills]
 